server {
    listen 80;
<<<<<<< HEAD
    server_name finishlinefinal.duckdns.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name finishlinefinal.duckdns.org;

    ssl_certificate     /etc/letsencrypt/live/finishlinefinal.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/finishlinefinal.duckdns.org/privkey.pem;
=======
    server_name localhost;
>>>>>>> imagenes

    root /var/www/html;
    client_max_body_size 50M;

    location / {
        index index.php index.html;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
<<<<<<< HEAD
}
=======
}
>>>>>>> imagenes
